---
title: "R Notebook"
output: html_notebook
---

# Data Reading and Processing 
## Imports
```{r}
library(ggplot2)
library(dplyr)
```

## Read the dataset
```{r}
 all_movies <- read.csv("./Datasets/tmdb-movies.csv")
```

```{r}
all_movies[0:3,]
```
## remove unncessary columns
```{r}
all_movies = all_movies[,!(names(all_movies) %in% c('imdb_id','homepage','director','overview','tagline','keywords','budget_adj','revenue_adj','production_companies','original_title'))]
all_movies[1,]
```

## remove NA rows
```{r}
nrow(all_movies)
all_movies = all_movies[rowSums(is.na(all_movies)) == 0,]
nrow(all_movies)
```

### genres to vector
```{r}
all_movies$genres = strsplit(all_movies$genres, "\\|")
```

### spread genres
```{r}
all_movies = all_movies %>%
  unnest(genres)
```


# EDA

## data summary
```{r}
summary(all_movies)
```

## Genres Popularity
```{r}
ggplot(all_movies, aes(genres)) + geom_bar(stat = 'count') + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```

```{r}
ggplot(all_movies, 
        aes(x = factor(1),fill = factor(genres))) + 
  geom_bar(stat = "count") + 
  scale_y_continuous(breaks = seq(0,12,3), labels = c("0", "25%", "50%", "75%", "100%")) + 
  coord_polar(theta='y') +
  theme(axis.text.y = element_blank(), 
        axis.title.y = element_blank(), 
        axis.ticks.y = element_blank(),
        axis.title.x = element_blank())
```


## Average budget per genre

```{r}
budget_per_genre = aggregate(list(budget=all_movies$budget), by=list(genre=all_movies$genres), FUN=mean)
budget_per_genre
```

```{r}
ggplot(budget_per_genre, aes(genre, budget), label=as.character(round(x,2))) + geom_col() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```

## Average revenue per genre

```{r}
revenue_per_genre = aggregate(list(revenue=all_movies$revenue), by=list(genre=all_movies$genres), FUN=mean)
revenue_per_genre[order(revenue_per_genre$revenue, decreasing = TRUE),]
```


```{r}
ggplot(revenue_per_genre[1:10,], aes(genre, revenue), label=as.character(round(x,2))) + geom_col() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```



## Cast influence on revenue | top 30
```{r}
all_movies = all_movies %>%
  mutate(cast=strsplit(cast, "\\|")) %>% 
  unnest(cast)
```

```{r}
revenue_per_cast = aggregate(all_movies$revenue, by=list(cast=all_movies$cast), FUN=mean)
revenue_per_cast = revenue_per_cast[order(revenue_per_cast$x, decreasing = TRUE),]
revenue_per_cast
```


```{r}
ggplot(revenue_per_cast[1:30,], aes(cast, x)) + geom_col() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```

## Popularity and revenue

```{r}
ggplot(all_movies, aes(popularity, revenue)) + geom_point() + xlim(0, 10)
```


--------------------------------------------------


# Inferential statistics
```{r}
regression_model = lm(data = all_movies, formula = revenue ~ budget)
regression_model
```

```{r}
summary(regression_model)
```



```{r}
ggplot(all_movies, aes(budget, revenue)) + geom_point() + geom_smooth(method = 'lm', col='blue')
```







